### ISSUE TITLE
novor buffer undefined

### ISSUE THREAD

**Issue by jallmer** [savastakan/dnmso#3]
Novor processing not working.
Error:
H:\github\dnmso\data\Novor>node success-rate-checker-11b.js
TypeError [ERR_INVALID_ARG_TYPE]: The "buf" argument must be one of type Buffer,
 TypedArray, or DataView. Received type undefined
    at StringDecoder.write (string_decoder.js:74:11)
    at CsvParserStream._transform (H:\github\dnmso\data\Novor\node_modules\@fast
-csv\parse\build\src\CsvParserStream.js:58:50)
    at CsvParserStream.Transform._read (_stream_transform.js:190:10)
    at CsvParserStream.Transform._write (_stream_transform.js:178:12)
    at doWrite (_stream_writable.js:410:12)
    at writeOrBuffer (_stream_writable.js:394:5)
    at CsvParserStream.Writable.write (_stream_writable.js:294:11)
    at Promise.then.mgf (H:\github\dnmso\data\Novor\success-rate-checker-11b.js:
58:12)
    at process._tickCallback (internal/process/next_tick.js:68:7)

node version: 10.15.1

**Comment by gokaybiz** [comment]
It was removing the comment lines of Novor, and giving errors when comments was not there. I fixed it.
Could you try with last commit?

**Comment by jallmer** [comment]
One error down.
Next one:
H:\github\dnmso\data\Novor>node success-rate-checker-11b.js
TypeError: Cannot read property 'trim' of undefined
    at CsvParserStream.parse.on.on.row (H:\github\dnmso\data\Novor\success-rate-
checker-11b.js:49:41)
    at CsvParserStream.emit (events.js:189:13)
    at CsvParserStream.emit (H:\github\dnmso\data\Novor\node_modules\@fast-csv\p
arse\build\src\CsvParserStream.js:49:22)
    at addChunk (_stream_readable.js:284:12)
    at readableAddChunk (_stream_readable.js:265:11)
    at CsvParserStream.Readable.push (_stream_readable.js:220:10)
    at CsvParserStream.Transform.push (_stream_transform.js:151:32)
    at CsvParserStream.pushRow (H:\github\dnmso\data\Novor\node_modules\@fast-cs
v\parse\build\src\CsvParserStream.js:185:22)
    at transformRow (H:\github\dnmso\data\Novor\node_modules\@fast-csv\parse\bui
ld\src\CsvParserStream.js:128:33)
    at callValidator (H:\github\dnmso\data\Novor\node_modules\@fast-csv\parse\bu
ild\src\transforms\RowTransformerValidator.js:74:24)

**Comment by gokaybiz** [comment]
Could I see your input file?

**Comment by jallmer** [comment]
I use the one linked in github.

Am Fr., 22. Mai 2020 um 17:57 Uhr schrieb gokaybiz <notifications@github.com
